[package]
name = "flow"
version = "0.1.0"
authors = ["Dylan Anthony <contact@dylananthony.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = "2.0.0"
async-std = "1.6.5"
dotenv = "0.15.0"
serde = { version = "1.0.117", features = ["derive"] }
base64 = "0.13.0"
color-eyre = "0.5.6"
