[[workflows]]
name = "Start New Task"

    [[workflows.steps]]
    type = "SelectIssue"
    status = "selected"

    [[workflows.steps]]
    type = "TransitionIssue"
    status = "Development"

    [[workflows.steps]]
    type = "SwitchBranches"

[[workflows]]
name = "Finish Development"

    [[workflows.steps]]
    type = "RebaseBranch"
    to = "main"

    [[workflows.steps]]
    type = "TransitionIssue"
    status = "Done"

[jira]
url = "https://triaxtec.atlassian.net"
project = "FLOW"
